apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: cloud-sdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-sdd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
